# POSTGRES
spring.datasource.url=jdbc:postgresql://34.173.25.245:5432/presence_hub
spring.datasource.username=hub_user
spring.datasource.password=securepassword
server.port=80
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
gcp.bucket.url=https://storage.cloud.google.com/presence_hub_certificados/
validate.url=/certificados/upload
security.jwt.expiracao=300
security.jwt.chave-assinatura=YSBsZW1icmUgw6kgYnJhbmNh

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
