jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o Java para o build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build do projeto com Maven
      - name: Build project
        run: |
          cd backend/presence-hub-back
          mvn clean package -DskipTests

      # 4. Transferir o arquivo JAR para a VM no GCP via SCP
      - name: Transfer JAR to GCP VM
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "backend/presence-hub-back/target/*.jar"
          target: "/home/${{ secrets.GCP_VM_USER }}/app/"

      # 5. Garantir que a pasta de destino existe
      - name: Ensure app directory exists
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/${{ secrets.GCP_VM_USER }}/app
            chmod 755 /home/${{ secrets.GCP_VM_USER }}/app

      # 6. Conectar via SSH e iniciar a aplicação
      - name: Deploy and run application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command_timeout: 20m
          script: |
            # Finalizar instâncias antigas, se existirem
            pkill -f 'java -jar' || true
            
            # Iniciar nova instância em segundo plano com o caminho correto
            nohup java -jar /home/${{ secrets.GCP_VM_USER }}/app/backend/presence-hub-back/target/presence-hub-0.0.1-SNAPSHOT.jar > /home/${{ secrets.GCP_VM_USER }}/app/app.log 2>&1 &
            
            # Remover processo da sessão para evitar problemas no runner
            disown
            
            # Verificar se o processo foi iniciado corretamente
            sleep 5
            ps aux | grep '[j]ava -jar'
