name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use the GCP registry
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/seu-projeto:${{ github.sha }} .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/presence-hub-back:${{ github.sha }}

  notify-spinnaker:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Spinnaker Deployment
        run: |
          curl -X POST "https://spinnaker-endpoint/api/v1/webhook" \
          -H "Content-Type: application/json" \
          -d '{
                "artifacts": [{
                  "type": "docker/image",
                  "name": "gcr.io/${{ secrets.GCP_PROJECT_ID }}/seu-projeto",
                  "reference": "gcr.io/${{ secrets.GCP_PROJECT_ID }}/seu-projeto:${{ github.sha }}"
                }]
              }'
        env:
          SPINNAKER_TOKEN: ${{ secrets.SPINNAKER_TOKEN }}