name: Deploy to GCP

on:
  push:
    branches:
      - master # Define o branch que dispara o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o Java para o build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build do projeto com Maven
      - name: Build project
        run: mvn clean package -DskipTests

      # 4. Transferir o arquivo JAR para a VM no GCP via SCP
      - name: Transfer JAR to GCP VM
        uses: appleboy/scp-action@v0.2.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "target/*.jar" # Caminho do JAR gerado pelo Maven
          target: "/home/${{ secrets.GCP_VM_USER }}/app/"

      # 5. Conectar via SSH e iniciar a aplicação
      - name: Deploy and run application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/${{ secrets.GCP_VM_USER }}/app/*.jar > app.log 2>&1 &
